name: molten_navigationbar_flutter
description: An animated bottom navigation bar with many parameters to tweak.
version: 0.0.1
homepage: https://github.com/AymanProjects/Molten_BottomNavBar_Flutter

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: